# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=100)),
                ('subscription_queue', models.CharField(max_length=100)),
                ('resourceID', models.CharField(max_length=100)),
            ],
        ),
    ]
